package io.quarkmind.sc2.replay;

import io.quarkmind.domain.UpgradeType;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.assertTrue;

@Tag("report")
class UpgradeMappingGeneratorTest {

    @Test
    void generateUpgradeMapping() throws IOException {
        var upgrades = Arrays.stream(UpgradeType.values())
                .map(UpgradeType::pythonName)
                .collect(Collectors.toList());

        var sb = new StringBuilder();
        sb.append("# Generated by UpgradeMappingGeneratorTest — do not edit manually\n");
        sb.append("UPGRADES = [\n");
        for (int i = 0; i < upgrades.size(); i++) {
            sb.append("    \"").append(upgrades.get(i)).append("\",\n");
        }
        sb.append("]\n");

        var outputPath = Path.of("../quarkmind-classifier/src/upgrade_mapping.py");
        Files.createDirectories(outputPath.getParent());
        Files.writeString(outputPath, sb.toString());

        assertTrue(upgrades.size() >= 82,
                "Expected ≥82 upgrades but found " + upgrades.size());
        System.out.printf("Wrote %d upgrades to %s%n", upgrades.size(), outputPath.toAbsolutePath());
    }
}
