package io.quarkmind.domain;

public enum UnitType {
    // Protoss
    PROBE(Race.PROTOSS), ZEALOT(Race.PROTOSS), STALKER(Race.PROTOSS),
    IMMORTAL(Race.PROTOSS), COLOSSUS(Race.PROTOSS), CARRIER(Race.PROTOSS),
    DARK_TEMPLAR(Race.PROTOSS), HIGH_TEMPLAR(Race.PROTOSS), ARCHON(Race.PROTOSS),
    OBSERVER(Race.PROTOSS), VOID_RAY(Race.PROTOSS),
    ADEPT(Race.PROTOSS), DISRUPTOR(Race.PROTOSS), SENTRY(Race.PROTOSS),
    PHOENIX(Race.PROTOSS), ORACLE(Race.PROTOSS), TEMPEST(Race.PROTOSS),
    MOTHERSHIP(Race.PROTOSS),
    WARP_PRISM(Race.PROTOSS), WARP_PRISM_PHASING(Race.PROTOSS),
    INTERCEPTOR(Race.PROTOSS), ADEPT_PHASE_SHIFT(Race.PROTOSS),
    // Zerg
    ZERGLING(Race.ZERG), ROACH(Race.ZERG), HYDRALISK(Race.ZERG),
    MUTALISK(Race.ZERG), ULTRALISK(Race.ZERG),
    BROOD_LORD(Race.ZERG), CORRUPTOR(Race.ZERG), INFESTOR(Race.ZERG),
    SWARM_HOST(Race.ZERG), VIPER(Race.ZERG), QUEEN(Race.ZERG),
    RAVAGER(Race.ZERG), LURKER(Race.ZERG),
    DRONE(Race.ZERG), OVERLORD(Race.ZERG), OVERSEER(Race.ZERG),
    BANELING(Race.ZERG),
    LOCUST(Race.ZERG), BROODLING(Race.ZERG), INFESTED_TERRAN(Race.ZERG),
    CHANGELING(Race.ZERG),
    EGG(Race.ZERG),
    // Terran
    MARINE(Race.TERRAN), MARAUDER(Race.TERRAN), MEDIVAC(Race.TERRAN),
    SIEGE_TANK(Race.TERRAN), SIEGE_TANK_SIEGED(Race.TERRAN), THOR(Race.TERRAN),
    VIKING(Race.TERRAN),
    GHOST(Race.TERRAN), RAVEN(Race.TERRAN), BANSHEE(Race.TERRAN),
    BATTLECRUISER(Race.TERRAN), CYCLONE(Race.TERRAN), LIBERATOR(Race.TERRAN),
    WIDOW_MINE(Race.TERRAN),
    SCV(Race.TERRAN), REAPER(Race.TERRAN), HELLION(Race.TERRAN),
    HELLBAT(Race.TERRAN), MULE(Race.TERRAN),
    VIKING_ASSAULT(Race.TERRAN), LIBERATOR_AG(Race.TERRAN), AUTO_TURRET(Race.TERRAN),
    // Fallback
    UNKNOWN(null);

    private final Race race;

    UnitType(Race race) {this.race = race;}

    public Race race()  {return race;}

    public boolean isWorker() {
        return this == PROBE || this == SCV || this == DRONE;
    }

}
